site_name: Langchain Dev Utils
site_url: https://tbice123123.github.io/langchain-dev-utils/
theme:
  name: material
  features:
    - navigation.tabs         
    - navigation.sections      
    - navigation.expand        
    - navigation.instant      
    - navigation.tracking      
    - navigation.top          
    - search.suggest           
    - search.highlight         
    - search.share             
    - content.code.copy       
    - content.code.annotate    
    - content.tabs.link       
    - content.tooltips        
    - content.footnote.tooltips 
  palette:
    - scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  language: zh
repo_name: tbice123123/langchain-dev-utils
repo_url: https://github.com/tbice123123/langchain-dev-utils


markdown_extensions:
  - admonition         
  - pymdownx.details    
  - pymdownx.superfences 
  - pymdownx.tabbed:
      alternate_style: true     
  - pymdownx.highlight  
  - attr_list           
  - md_in_html          
  - tables              
  - toc                 
  - footnotes     
  - def_list       
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg       
  - pymdownx.tasklist   
  - pymdownx.mark     
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format            


plugins:
  - search
  - i18n:
      docs_structure: folder 
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
          - Overview: index.md
          - Getting Started:
            - Installation: getting-started-guide/installation.md
            - Chat Model Management: getting-started-guide/chat.md
            - Embedding Model Management: getting-started-guide/embedding.md
            - Formatting Sequences: getting-started-guide/format.md
            - Message Processing: getting-started-guide/message.md
            - Tool Calling Processing: getting-started-guide/tool.md
            - Add Human-in-the-Loop Support in Tool Calling: getting-started-guide/human-in-the-loop.md
          - Advanced Guides:
            - OpenAI Compatible API Integration:
              - Overview: adavance-guide/openai-compatible/overview.md
              - Creating and Using Chat Models: adavance-guide/openai-compatible/chat.md
              - Creating and Using Embedding Models: adavance-guide/openai-compatible/embedding.md
              - Integration with Model Management: adavance-guide/openai-compatible/register.md
            - Middleware:
              - Overview: adavance-guide/middleware/overview.md
              - Task Planning: adavance-guide/middleware/plan.md
              - Model Routing: adavance-guide/middleware/router.md
              - Agent Handoff: adavance-guide/middleware/handoffs.md
              - Tool Call Repair: adavance-guide/middleware/tool-call-repair.md
              - Format System Prompts: adavance-guide/middleware/format.md
              - LangChain Built-in Middleware Extensions: adavance-guide/middleware/official.md
            - Subagent Tools (Agent as Tool): adavance-guide/multi-agent.md
            - Prebuilt State-Graph Building Functions: adavance-guide/graph.md
          - API Reference:
            - Agent Development Module API Reference: api-reference/agent.md
            - Chat Model Management Module API Reference: api-reference/chat_model.md
            - Embedding Model Management Module API Reference: api-reference/embeddings.md
            - Message Handling Module API Reference: api-reference/message_convert.md
            - Tool Calling Handling Module API Reference: api-reference/tool_calling.md
            - State-Graph Building Functions Module API Reference: api-reference/graph.md
          - Usage Examples: example-project.md
          
        - locale: zh
          name: 中文
          build: true
          nav:
          - 概述: index.md
          - 入门指南:
            - 安装: getting-started-guide/installation.md
            - 对话模型管理: getting-started-guide/chat.md
            - 嵌入模型管理: getting-started-guide/embedding.md
            - 格式化序列: getting-started-guide/format.md
            - 消息处理: getting-started-guide/message.md
            - 工具调用处理: getting-started-guide/tool.md
            - 为工具调用添加人工审核: getting-started-guide/human-in-the-loop.md
          - 高级指南:
            - OpenAI 兼容 API 集成: 
              - 概述: adavance-guide/openai-compatible/overview.md
              - 对话模型的创建与使用: adavance-guide/openai-compatible/chat.md
              - 嵌入模型的创建与使用: adavance-guide/openai-compatible/embedding.md
              - 与模型管理功能集成: adavance-guide/openai-compatible/register.md
            - 中间件: 
              - 概述: adavance-guide/middleware/overview.md
              - 任务规划: adavance-guide/middleware/plan.md
              - 模型路由: adavance-guide/middleware/router.md
              - 智能体交接: adavance-guide/middleware/handoffs.md
              - 工具调用修复: adavance-guide/middleware/tool-call-repair.md
              - 格式化系统提示词: adavance-guide/middleware/format.md
              - LangChain内置中间件扩展: adavance-guide/middleware/official.md
            - 子智能体工具（Agent as Tool）: adavance-guide/multi-agent.md
            - 预置状态图构建函数: adavance-guide/graph.md 
          - API 参考: 
            - 智能体开发模块 API参考: api-reference/agent.md
            - 对话模型管理模块 API参考: api-reference/chat_model.md
            - 嵌入模型管理模块 API参考: api-reference/embeddings.md
            - 消息处理模块 API参考: api-reference/message_convert.md
            - 工具调用处理模块 API参考: api-reference/tool_calling.md
            - 状态图构建函数模块 API参考: api-reference/graph.md
          - 使用示例: example-project.md
          
          
